<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="bogon" name="org.quickstart.testng.samples.EmployeeDirectoryTest" tests="5" failures="1" timestamp="22 十一月 2017 02:31:16 GMT" time="0.530" errors="0">
  <testcase name="checkFirstPersonNameInTheDirectory" time="0.026" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="shouldThrowExceptionWhenAccessingFirstPersonOnEmptyDirectory" time="0.001" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="checkFirstNameFunction" time="0.489" classname="org.quickstart.testng.samples.EmployeeDirectoryTest">
    <failure type="org.mockito.exceptions.verification.TooManyActualInvocations" message="
iPerson.getFullName();
Wanted 1 time:
-&gt; at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
But was 2 times. Undesired invocation:
-&gt; at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
">
      <![CDATA[org.mockito.exceptions.verification.TooManyActualInvocations: 
iPerson.getFullName();
Wanted 1 time:
-> at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
But was 2 times. Undesired invocation:
-> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

	at org.quickstart.testng.samples.EmployeeDirectoryTest.checkFirstNameFunction(EmployeeDirectoryTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkFirstNameFunction -->
  <testcase name="addPersonToEmployeeDirectory" time="0.011" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
  <testcase name="checkFirstNameFunctionInvocation" time="0.003" classname="org.quickstart.testng.samples.EmployeeDirectoryTest"/>
</testsuite> <!-- org.quickstart.testng.samples.EmployeeDirectoryTest -->
